name: revelation
description: "Revelation Study app."
publish_to: 'none'
version: 1.0.4+125

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # flutter.dev packages
  go_router: ^17.0.1 
  flutter_svg: ^2.2.3
  flutter_markdown: ^0.7.7
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4
  path_provider: ^2.1.5

  # dart.dev packages
  web: ^1.1.1
  intl: ^0.20.2

  # 3d party packages
  window_manager: ^0.5.1
  flutter_cache_manager: ^3.4.1
  get_it: ^8.3.0
  provider: ^6.1.5
  logger: ^2.6.2
  package_info_plus: ^9.0.0
  xml: ^6.6.1
  float_column: ^4.0.3
  styled_text: ^8.1.0
  supabase_flutter: ^2.12.0
  flutter_colorpicker: ^1.1.0
  vector_math: ^2.2.0
  image: ^4.7.2
  audioplayers: ^6.5.1
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  unorm_dart: ^0.3.2
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter.dev packages
  flutter_lints: ^6.0.0

  # dart.dev packages
  build_runner: ^2.10.5

  # 3d party packages
  flutter_launcher_icons: ^0.14.4
  msix: ^3.16.9
  drift_dev: ^2.30.1

msix_config:
  display_name: Revelation.Win
  identity_name: AI11.RevelationWin
  publisher_display_name: AI11
  publisher: CN=B37F48EC-C643-42C2-82FB-3DFB514F5E74
  languages: en, es, uk, ru
  store: true
  msix_version: 1.0.129.0
  logo_path: .\assets\images\UI\app_icon.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - CHANGELOG.md
    - assets/data/
    - assets/data/topics/
    - assets/images/UI/
    - assets/images/Topics/
    - assets/images/PrimarySources/
    - assets/sounds/

  fonts:
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo/Arimo.ttf
          weight: 400

